version: "3.8"
services:

  auth-db:
    image: postgres
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"

  auth-service:
    build: ./auth-service
    depends_on:
      - auth-db
    ports:
      - "8082:8082"
